<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('details')->insert([
            ['id' => 1,'book_id' => 1, 'author' => 'Vincent Low', 'publisher' => 'Bertelsmann', 'year' => 1999, 'description' => "The secluded life of a young girl might turn out differently as a lost friend enters her life. The lost friend claims the young girl is a relative, but that this information was lost in the hospital until recently. This person would like to stay over and catch up on lost time. Suspicious of this situation, but somewhat trusting of this lost friend, the young girl somewhat hesitantly agrees to the proposal, the situation is all too strange, it's best to get more information as soon as possible. But what if this lost friend is wrong about all this. Or what if the wrong person was picked for this. How could an ordinary young girl end up in a situation like this. No turning back now though."],
            ['id' => 2, 'book_id' => 2, 'author' => 'Carrie Blackburn', 'publisher' => 'Thomson Reuters', 'year' => 2008, 'description' => "The wave roared towards them with speed and violence they had not anticipated. They both turned to run but by that time it was too late. The wave crashed into their legs sweeping both of them off of their feet. They now found themselves in a washing machine of saltwater, getting tumbled and not know what was up or down. Both were scared, not knowing how this was going to end, but it was by far the best time of the trip thus far."],
            ['id' => 3, 'book_id' => 3, 'author' => 'Angela Hall', 'publisher' => 'Bertelsmann', 'year' => 2002, 'description' => "They had always called it the green river. It made sense. The river was green. The river likely had a different official name, but to everyone in town, it was and had always been the green river. So it was with great surprise that on this day the green river was a fluorescent pink."],
            ['id' => 4, 'book_id' => 4, 'author' => 'Angela Hall', 'publisher' => 'Thomson Reuters', 'year' => 2001, 'description' => "'Ingredients for life', said the backside of the truck. They mean food, but really food is only 1 ingredient of life. Life has so many more ingredients such as pain, happiness, laughter, joy, tears, and smiles. Life also has hard work, easy play, sleepless nights, and sunbathing by the ocean. Love, hatred, envy, self-assurance, and fear could be just down aisle 3 ready to be bought when needed. How I wish I could pull ingredients like these off shelves in a store."],
            ['id' => 5, 'book_id' => 5, 'author' => 'Courtney Rivera', 'publisher' => 'Penguin Random House', 'year' => 2021, 'description' => "He was aware there were numerous wonders of this world including the unexplained creations of humankind that showed the wonder of our ingenuity. There are huge heads on Easter Island. There are the Egyptian pyramids. There’s Stonehenge. But he now stood in front of a newly discovered monument that simply didn't make any sense and he wondered how he was ever going to be able to explain it."],
            ['id' => 6, 'book_id' => 6, 'author' => 'Carrie Blackburn', 'publisher' => 'Penguin Random House', 'year' => 2004, 'description' => "The coin hovered in the air, spinning over and over again. It reached its peak and began to descend. Both boys were pleading with it to land a certain way but the coin had already made up its mind on what it was going to do."],
            ['id' => 7, 'book_id' => 7, 'author' => 'Poppy Chapman', 'publisher' => 'Hachette Livre', 'year' => 2013, 'description' => "It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust."],
            ['id' => 8, 'book_id' => 8, 'author' => 'Naomi Burke', 'publisher' => 'Hachette Livre', 'year' => 2002, 'description' => "The red line moved across the page. With each millimeter it advanced forward, something changed in the room. The actual change taking place was difficult to perceive, but the change was real. The red line continued relentlessly across the page and the room would never be the same."],
            ['id' => 9, 'book_id' => 9, 'author' => 'Vincent Low', 'publisher' => 'Bertelsmann', 'year' => 2021, 'description' => "Trees. It was something about the trees. The way they swayed with the wind in unison. The way they shaded the area around them. The sounds of their leaves in the wind and the creaks from the branches as they sway, The trees were making a statement that I just couldn't understand."],
            ['id' => 10, 'book_id' => 10, 'author' => 'Courtney Rivera', 'publisher' => 'HarperCollins', 'year' => 2003, 'description' => "A two-inch layer of freshly fallen snow covered the yard. Stacey peeked outside. To most, it would have been a beautiful sight worthy of taking a photo to put on Instagram. For Stacey, it meant something different. The first snow of the year brought back the witches as the fairies in the yard had to seek shelter to avoid the cold."],
            ['id' => 11, 'book_id' => 11, 'author' => 'Poppy Chapman', 'publisher' => 'Bertelsmann', 'year' => 2021, 'description' => "'Where do they get a random paragraph?' he wondered as he clicked the generate button. Do they just write a random paragraph or do they get it somewhere? At that moment he read the random paragraph and realized it was about random paragraphs and his world would never be the same."],
            ['id' => 12, 'book_id' => 12, 'author' => 'Lauren Reilly', 'publisher' => 'HarperCollins', 'year' => 2003, 'description' => "She has seen this scene before. It had come to her in dreams many times before. She had to pinch herself to make sure it wasn't a dream again. As her fingers squeezed against her arm, she felt the pain. It was this pain that immediately woke her up."],
            ['id' => 13, 'book_id' => 13, 'author' => 'Carrie Blackburn', 'publisher' => 'Macmillan Publishers', 'year' => 2000, 'description' => "The secluded life of a young girl might turn out differently as a lost friend enters her life. The lost friend claims the young girl is a relative, but that this information was lost in the hospital until recently. This person would like to stay over and catch up on lost time. Suspicious of this situation, but somewhat trusting of this lost friend, the young girl somewhat hesitantly agrees to the proposal, the situation is all too strange, it's best to get more information as soon as possible. But what if this lost friend is wrong about all this. Or what if the wrong person was picked for this. How could an ordinary young girl end up in a situation like this. No turning back now though."],
            ['id' => 14, 'book_id' => 14, 'author' => 'Lauren Reilly', 'publisher' => 'Macmillan Publishers', 'year' => 2021, 'description' => "The wave roared towards them with speed and violence they had not anticipated. They both turned to run but by that time it was too late. The wave crashed into their legs sweeping both of them off of their feet. They now found themselves in a washing machine of saltwater, getting tumbled and not know what was up or down. Both were scared, not knowing how this was going to end, but it was by far the best time of the trip thus far."],
            ['id' => 15, 'book_id' => 15, 'author' => 'Gabrielle Phillips', 'publisher' => 'Bertelsmann', 'year' => 2004, 'description' => "'Ingredients for life', said the backside of the truck. They mean food, but really food is only 1 ingredient of life. Life has so many more ingredients such as pain, happiness, laughter, joy, tears, and smiles. Life also has hard work, easy play, sleepless nights, and sunbathing by the ocean. Love, hatred, envy, self-assurance, and fear could be just down aisle 3 ready to be bought when needed. How I wish I could pull ingredients like these off shelves in a store."],
            ['id' => 16, 'book_id' => 16, 'author' => 'Bailey Beck', 'publisher' => 'Scholastic Corporation', 'year' => 2001, 'description' => "He was aware there were numerous wonders of this world including the unexplained creations of humankind that showed the wonder of our ingenuity. There are huge heads on Easter Island. There are the Egyptian pyramids. There’s Stonehenge. But he now stood in front of a newly discovered monument that simply didn't make any sense and he wondered how he was ever going to be able to explain it."],
            ['id' => 17, 'book_id' => 17, 'author' => 'Vincent Low', 'publisher' => 'Scholastic Corporation', 'year' => 2021, 'description' => "The coin hovered in the air, spinning over and over again. It reached its peak and began to descend. Both boys were pleading with it to land a certain way but the coin had already made up its mind on what it was going to do."],
            ['id' => 18, 'book_id' => 18, 'author' => 'Gabrielle Phillips', 'publisher' => 'Bertelsmann', 'year' => 2005, 'description' => "They had always called it the green river. It made sense. The river was green. The river likely had a different official name, but to everyone in town, it was and had always been the green river. So it was with great surprise that on this day the green river was a fluorescent pink."],
            ['id' => 19, 'book_id' => 19, 'author' => 'Bailey Beck', 'publisher' => 'Scholastic Corporation', 'year' => 2021, 'description' => "It went through such rapid contortions that the little bear was forced to change his hold on it so many times he became confused in the darkness, and could not, for the life of him, tell whether he held the sheep right side up, or upside down. But that point was decided for him a moment later by the animal itself, who, with a sudden twist, jabbed its horns so hard into his lowest ribs that he gave a grunt of anger and disgust."],
            ['id' => 20, 'book_id' => 20, 'author' => 'Vincent Low', 'publisher' => 'Bertelsmann', 'year' => 2007, 'description' => "The red line moved across the page. With each millimeter it advanced forward, something changed in the room. The actual change taking place was difficult to perceive, but the change was real. The red line continued relentlessly across the page and the room would never be the same."],
        ]);
    }
}